Added GetCurrencyBySymbol
noobsmuc/CoinmarketcapClient pull request #5
Opened 2021-10-25 08:34 UTC by bakingam1983

Added GetCurrencyBySymbol

2021-10-26 11:42 UTC, DominikLindemann requested changes
please use camelCase overall

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/CoinmarketcapClient.cs
> +        Currency ICoinmarketcapClient.GetCurrencyBySymbol(string Symbol)
please write **s**ymbol in lowercase

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/CoinmarketcapClient.cs
> +        Currency ICoinmarketcapClient.GetCurrencyBySymbol(string Symbol, string convertCurrency)
please write **s**ymbol in lowercase

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/CoinmarketcapClient.cs
> +        public IEnumerable<Currency> GetCurrencyBySymbolList(string[] SymbolList)
please write **s**ymbolList in lowercase

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/CoinmarketcapClient.cs
> +        public IEnumerable<Currency> GetCurrencyBySymbolList(string[] SymbolList, string convertCurrency)
please write **s**ymbolList in lowercase

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/CoinmarketcapClient.cs
> +        private IEnumerable<Currency> CurrencyBySymbolList(List<string> SymbolList, string convertCurrency)
please write **s**ymbolList in lowercase

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/ICoinmarketcapClient.cs
> +        IEnumerable<Currency> GetCurrencyBySymbolList(string[] SymbolList);
please write **s**ymbolList in lowercase

2021-10-26 11:42 UTC, DominikLindemann commented on CoinmarketcapClient/ICoinmarketcapClient.cs
> +        IEnumerable<Currency> GetCurrencyBySymbolList(string[] SymbolList, string convertCurrency);
please write **s**ymbolList in lowercase

2021-10-26 14:05 UTC, bakingam1983 commented
I' ve made in the second commit...

2021-11-03 09:52 UTC, DominikLindemann approved these changes

2021-11-03 09:52 UTC, merged